package com.lk.lms.ws.consumer.co024;

import java.util.Map;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import com.lk.lms.common.service.IfLogService;
import com.lk.lms.common.service.WebClientInterface;
import com.lk.lms.common.util.LmsConstants;
import com.lk.lms.common.util.LmsUtil;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-10-11T10:40:34.966+09:00
 * Generated source version: 3.2.5
 *
 */
@Component("co024SOClient")
public final class CO024SOClient implements WebClientInterface {
	
	private Logger logger = LoggerFactory.getLogger(this.getClass());
    
    @Autowired
    private IfLogService ifLogService;
    
    private static final QName SERVICE_NAME = new QName("http://skgas.co.kr/CO024", "CO024_SOService");
    
    private CO024SOClient() {
    }

	@Override
	public String execute(Map<Object, Object> map) {
		URL wsdlURL = CO024SOService.WSDL_LOCATION;

        CO024SOService ss = new CO024SOService(wsdlURL, SERVICE_NAME);
        CO024SO port = ss.getHTTPPort();

        // 인증, endpoint 조정
        LmsUtil.wsAuth(port);

        String ifId = "CO024";
        String uuid = ifLogService.generateUUID();
        String rtnCd = "P"; // S:Success, E:Error, P:Processing
        String rtnMsg = "";

        com.lk.lms.ws.consumer.co024.DTCO024SR dtsr = new DTCO024SR();
        try {
            // 비즈니스 로직에 의한 조회값 설정
        	com.lk.lms.ws.consumer.co024.DTCO024S dts = new com.lk.lms.ws.consumer.co024.DTCO024S();
            
            dts.setSETID((String) map.get("setId"));     //set id
            dts.setACCNUTYEAR((String) map.get("accnutYear")); //회계년도
            
           /* dts.setSETID("02-06");     //set id
            dts.setACCNUTYEAR("2018"); //회계년도
*/            
            // 송신 내역 로그
            ifLogService.insertLog(ifId, uuid, LmsConstants.IF_CONSUMER, LmsUtil.objToJsonStr(dts), rtnCd, rtnMsg);
            dtsr = port.co024SO(dts);
            
            // 수신 내역과 결과 로그
            rtnCd = "S";
            rtnMsg = "성공";
            ifLogService.updateLog(ifId, uuid, LmsUtil.objToJsonStr(dtsr), rtnCd, rtnMsg);
            
        } catch (Exception e) { 
            logger.error("Error",e);
            // 에러 결과 로그
            rtnCd = "E"; // S:Success, E:Error, P:Processing
            rtnMsg = e.getMessage().substring(0,80);
            ifLogService.exceptionIfLog(ifId, uuid, LmsConstants.IF_CONSUMER, LmsUtil.objToJsonStr(dtsr), rtnCd, rtnMsg);

            // method 반환값 조합
            //dtsr.setRTNCD("E");
            //dtsr.setMESSAGE(e.getMessage().substring(0,80));
        }
        
        // return JSON String
        return LmsUtil.objToJsonStr(dtsr);
	}

}
