package com.lk.lms.ws.consumer.co024;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-10-11T10:40:35.033+09:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://skgas.co.kr/CO024", name = "CO024_SO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface CO024SO {
	
	@WebMethod(operationName = "CO024_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_CO024_SR", targetNamespace = "http://skgas.co.kr/CO024", partName = "MT_CO024_SR")
    public DTCO024SR co024SO(
        @WebParam(partName = "MT_CO024_S", name = "MT_CO024_S", targetNamespace = "http://skgas.co.kr/CO024")
        DTCO024S mtCO024S
    );

}
